feat: Update Inbound & Outbound API defs and typescript definitions
mojaloop/thirdparty-scheme-adapter pull request #52
Opened 2021-03-08 14:14 UTC by sridharvoruganti

Closes #[2096](https://github.com/mojaloop/project/issues/2096) 

- Modify Inbound , Outbound and docker-contract API definitions accordance with new releases
- Use api-snippets typescript definitions in place of local types defined in index.d.ts (sdk-standard-components)

2021-03-08 20:36 UTC, kleyow commented on src/models/thirdparty.authorizations.interface.ts
> +// export interface InboundThirdpartyAuthorizationsPutRequest {
nit: remove?

2021-03-08 20:37 UTC, kleyow approved these changes
lgtm. I'd take this chance to update any snippets to v1_1 if possible, but this is a big diff so we can do that in a follow up PR if you'd like

2021-03-09 08:05 UTC, eoln requested changes
Great job is done @sridharvoruganti  
Few things need explanation/fixing
- why there are empty files: 
  - src/interface/inbound/api_interfaces/index.d.ts
  - src/interface/outbound/api_interfaces/index.d.ts
- please add `Sridar` to contributors :-D

2021-03-09 08:05 UTC, eoln commented on src/models/thirdparty.authorizations.interface.ts
> +// export interface InboundThirdpartyAuthorizationsPutRequest {
or leave doc comment

2021-03-09 08:05 UTC, eoln commented on test/unit/handlers/inbound-api.test.ts
> +    } as any
can't we drop `as any`  casting?

2021-03-09 08:05 UTC, eoln commented on test/unit/models/inbound/authorizations.model.test.ts
>        counter: '1'
maybe adding the type for `authenticationValue` would prevent as from casting `as any` later?

2021-03-09 09:43 UTC, sridharvoruganti commented on src/models/thirdparty.authorizations.interface.ts
> +// export interface InboundThirdpartyAuthorizationsPutRequest {
ok

2021-03-09 09:44 UTC, sridharvoruganti commented on package.json
> +    "@mojaloop/api-snippets": "^12.0.8",
ok removed

2021-03-09 09:54 UTC, eoln approved these changes
lgtm

2021-03-09 09:54 UTC, eoln commented on package.json
> +    "Sridhar Voruganti <sridhar.voruganti@modusbox.com>"
+1

2021-03-09 09:58 UTC, sridharvoruganti commented on .circleci/config.yml
> +  # temporarily disbaled as api-snippets is not compatible with existing license policy
ok will correct it

2021-03-09 10:02 UTC, sridharvoruganti commented
> lgtm. I'd take this chance to update any snippets to v1_1 if possible, but this is a big diff so we can do that in a follow up PR if you'd like

it's become big PR, will do any further changes in next PR

2021-03-09 10:02 UTC, merged