docs: add sequence diagrams for consent request OTP validation
mojaloop/thirdparty-scheme-adapter pull request #67
Opened 2021-03-23 01:31 UTC by kleyow

2021-03-23 07:05 UTC, eoln requested changes
let have svg generated files, and use them in docs - using puml server is unstable and often images aren't rendered at all.

2021-03-23 11:44 UTC, kleyow commented
done.

2021-03-23 12:43 UTC, eoln requested changes

2021-03-23 12:43 UTC, eoln commented on docs/sequence/DFSPOTPValidateModel.puml
> +@startuml DFSPOTPValidateModel
I would suggest:
- introducing two final states: success / errored -> where on errored we call  putConsentRequestsError
- introduce transitions for happy flow & corresponding states:  
   - validateOTP (from=start, to=OTPisValid)
   - requestScopes (from=OTPisValid, to=scopesReceived)
   - storeConsent(from=scopesReceived, to=succeed)
   
  Then you can implement this workflow as an extension of PersistenModel class

2021-04-06 06:12 UTC, eoln approved these changes

2021-04-06 11:43 UTC, merged