doc: add happy path for PISPLinkingModel sequence diagram
mojaloop/thirdparty-scheme-adapter pull request #87
Opened 2021-04-21 07:36 UTC by kleyow

Still WIP but want to get up for feedback before I sign off for the night.

2021-04-21 10:10 UTC, eoln requested changes
- let use `activate` just after receiving a call, not before
- let split this big happy flow into cases (WEB/OTP) and phases into separated files, so we will be able to inject some documentation text in between

2021-04-21 10:10 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +activate Switch
move to L94 and activate switch after DFSP_LM -> Switch: PUT /consentRequests/6789

2021-04-21 10:10 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +deactivate DFSP_LM
call saveToKVS() before `deactivate DFSP_LM`

2021-04-21 10:10 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +activate PISP_TP_IN
move activate after Switch -> PISP_TP_IN: PUT /consentRequests/6789

2021-04-21 10:10 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +deactivate PISP_TP_IN
move to L120, just before `rnote right of PISP_LM: state: webAuthenticationChannelResponseRecieved`

2021-04-21 10:10 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +deactivate PISP_LM
drop `deactivate PISP_LM` to express that model is listening on PUT `/consentReqeusts/8789`

2021-04-21 10:10 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +
let split the diagram here (on cases) so we can inject some text in documentation between phases

2021-04-21 10:28 UTC, eoln requested changes
more comments

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +
let split here

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +PATCH /linking/authenticate/6789
POST or PATCH?

maybe let use POST `/linking/request-consent/{ConsentRequestId}/authenticate`

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +validate both cases with one endpoint?
let propagate to the call payload the `authChannel` value which should be stored in the previous step when callback `PUT /consentReqeusts/{consentRequestId}` was called.

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +  authToken: '124356'
```suggestion
  authChannel: model.data.authChannel,
  authToken: '124356'
```

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +validate both cases with one endpoint?
when we send `authChannel` then we can easily mock simulator for proper behaviours and testing various scenarios

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +  make a request?
we should store results from the previous call to getScopes this data in the model state so we don't have to repeat it here.

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +deactivate DFSP_LM
drop `deactivate DFSP_LM` here to express the model is waiting on `PUT /consents/1a2b3c4d` from auth service OR use `saveToKVS()`to express preserving the state

2021-04-21 10:28 UTC, eoln commented on docs/sequence/PISPLinkingApi.puml
> +deactivate AUTH
let drop `deactivate AUTH` here and `activate AUTH` in L509 to express AUTH is sill processing

2021-04-21 11:53 UTC, kleyow commented
> * let use `activate` just after receiving a call, not before
> * let split this big happy flow into cases (WEB/OTP) and phases into separated files, so we will be able to inject some documentation text in between

I was actually considering using `autoactivate` or `++` or `--` notation and wanted to know other peoples thoughts are on that.

2021-04-21 13:59 UTC, eoln commented
let use autoactivate if it fits you, I wouldn't use `++` or `--` because they are too cryptic

2021-04-22 05:21 UTC, kleyow commented
autoactivate turned out to not be very intuiative so didn't bother to use it. addressed comments.

2021-04-22 07:24 UTC, eoln requested changes
- inbound server should send 202 back to switch ASAP for both diagrams

2021-04-22 07:24 UTC, eoln commented on docs/sequence/PISPLinkingOTPApi.puml
> +DFSP_TP_IN --> Switch: 202 Accepted
move to L75 -> there is a need to send 202 back to the switch asap

2021-04-22 07:24 UTC, eoln commented on docs/sequence/PISPLinkingOTPApi.puml
> +activate DFSP_LM
too early activation of DFSP_LM - move to L80

2021-04-22 07:24 UTC, eoln commented on docs/sequence/PISPLinkingOTPApi.puml
> +DFSP_TP_IN --> Switch: 202 Accepted
202 asap to switch -> move to L190

2021-04-22 07:24 UTC, eoln commented on docs/sequence/PISPLinkingOTPApi.puml
> +activate DFSP_LM
to early activation, move to L195, after `model.validateAuthToken()`

2021-04-22 07:24 UTC, eoln commented on docs/sequence/PISPLinkingOTPApi.puml
> +store the model with.
I see two possible solutions:
- we can create the second instance of the model using existing state data but with a new key and call saveToKVS
- or we can refactor save/load methods and add an optional parameters to specify special/new key.

2021-04-22 07:24 UTC, eoln commented on docs/sequence/PISPLinkingOTPApi.puml
> +loop for each scope in ""Consents.scopes""
maybe it would be better to consider bulk update instead of multiple calls - @lewisdaly ???

2021-04-22 16:40 UTC, eoln approved these changes

2021-04-22 16:41 UTC, merged